-- =========================================================
-- BLOQUE 5: NETFLIX + SPOTIFY + DISTRIBUIDORES + NOTIFICACIONES
-- Ejecutar después de los bloques anteriores.
-- =========================================================

alter table public.profiles add column if not exists notification_settings jsonb not null default '{"in_app":true,"browser":false}'::jsonb;
alter table public.netflix_accounts add column if not exists service text not null default 'netflix';
alter table public.support_tickets alter column account_id drop not null;
alter table public.support_tickets add column if not exists service text not null default 'netflix';
alter table public.support_tickets add column if not exists reported_email text;
alter table public.account_change_history add column if not exists service text not null default 'netflix';
alter table public.entertainment_content add column if not exists platform text not null default 'netflix';
update public.support_tickets set reported_email=account_email_snapshot where reported_email is null;

do $$ begin if not exists(select 1 from pg_constraint where conname='netflix_accounts_service_check') then alter table public.netflix_accounts add constraint netflix_accounts_service_check check(service in('netflix','spotify')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='support_tickets_service_check') then alter table public.support_tickets add constraint support_tickets_service_check check(service in('netflix','spotify')); end if; end $$;
do $$ begin if not exists(select 1 from pg_constraint where conname='entertainment_content_platform_check') then alter table public.entertainment_content add constraint entertainment_content_platform_check check(platform in('netflix','spotify')); end if; end $$;

drop index if exists public.netflix_account_email_unique_idx;
create unique index if not exists service_account_email_unique_idx on public.netflix_accounts(service,lower(current_email));

create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),sender_id uuid not null references public.profiles(id) on delete restrict,title text not null,message text not null,image_url text,created_at timestamptz not null default now());
create table if not exists public.notification_recipients(id uuid primary key default gen_random_uuid(),notification_id uuid not null references public.notifications(id) on delete cascade,recipient_id uuid not null references public.profiles(id) on delete cascade,read_at timestamptz,created_at timestamptz not null default now(),unique(notification_id,recipient_id));
create index if not exists notification_recipients_recipient_idx on public.notification_recipients(recipient_id,created_at desc);
alter table public.notifications enable row level security;
alter table public.notification_recipients enable row level security;
drop policy if exists notifications_select_visible on public.notifications;
drop policy if exists notification_recipients_select_visible on public.notification_recipients;
drop policy if exists notification_recipients_update_own on public.notification_recipients;
create policy notifications_select_visible on public.notifications for select to authenticated using(private.is_staff() or exists(select 1 from public.notification_recipients nr where nr.notification_id=notifications.id and nr.recipient_id=(select auth.uid())));
create policy notification_recipients_select_visible on public.notification_recipients for select to authenticated using(private.is_staff() or recipient_id=(select auth.uid()));
create policy notification_recipients_update_own on public.notification_recipients for update to authenticated using(recipient_id=(select auth.uid())) with check(recipient_id=(select auth.uid()));
grant select on public.notifications to authenticated;
grant select,update on public.notification_recipients to authenticated;

insert into storage.buckets(id,name,public) values('avatars','avatars',true),('notification-images','notification-images',true) on conflict(id) do update set public=true;
drop policy if exists avatar_public_read on storage.objects; drop policy if exists avatar_insert_own on storage.objects; drop policy if exists avatar_update_own on storage.objects; drop policy if exists notification_image_public_read on storage.objects; drop policy if exists notification_image_admin_insert on storage.objects;
create policy avatar_public_read on storage.objects for select to authenticated using(bucket_id='avatars');
create policy avatar_insert_own on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy avatar_update_own on storage.objects for update to authenticated using(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text) with check(bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy notification_image_public_read on storage.objects for select to authenticated using(bucket_id='notification-images');
create policy notification_image_admin_insert on storage.objects for insert to authenticated with check(bucket_id='notification-images' and private.is_admin());

create or replace function public.update_my_profile(p_full_name text,p_business_name text,p_whatsapp text,p_avatar_url text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid());v_result public.profiles;v_whatsapp text:=regexp_replace(coalesce(p_whatsapp,''),'\D','','g');
begin if v_user is null then raise exception 'Debes iniciar sesión.';end if;if length(trim(p_full_name))<3 then raise exception 'El nombre debe tener al menos 3 caracteres.';end if;if v_whatsapp<>'' and (length(v_whatsapp)<8 or length(v_whatsapp)>15) then raise exception 'El WhatsApp no es válido.';end if;update public.profiles set full_name=trim(p_full_name),business_name=nullif(trim(coalesce(p_business_name,'')),''),whatsapp=nullif(v_whatsapp,''),avatar_url=nullif(trim(coalesce(p_avatar_url,'')),'') where id=v_user returning * into v_result;return jsonb_build_object('full_name',v_result.full_name,'business_name',v_result.business_name,'whatsapp',v_result.whatsapp,'avatar_url',v_result.avatar_url);end;$$;
revoke all on function public.update_my_profile(text,text,text,text) from public,anon;grant execute on function public.update_my_profile(text,text,text,text) to authenticated;

create or replace function public.set_my_notification_preferences(p_in_app boolean,p_browser boolean) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid());v jsonb:=jsonb_build_object('in_app',coalesce(p_in_app,true),'browser',coalesce(p_browser,false));begin if v_user is null then raise exception 'Debes iniciar sesión.';end if;update public.profiles set notification_settings=v where id=v_user;return v;end;$$;
revoke all on function public.set_my_notification_preferences(boolean,boolean) from public,anon;grant execute on function public.set_my_notification_preferences(boolean,boolean) to authenticated;

create or replace function public.bulk_add_service_accounts(p_service text,p_account_type text,p_emails text[]) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_service text:=lower(trim(p_service));v_email text;v_raw text;v_inserted int:=0;v_duplicates int:=0;v_invalid int:=0;
begin if not private.is_admin() then raise exception 'Solo el administrador puede añadir cuentas.';end if;if v_service not in('netflix','spotify') then raise exception 'Plataforma no válida.';end if;foreach v_raw in array p_emails loop v_email:=lower(trim(coalesce(v_raw,'')));if v_email='' or v_email!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then v_invalid:=v_invalid+1;continue;end if;if exists(select 1 from public.netflix_accounts where service=v_service and lower(current_email)=v_email) then v_duplicates:=v_duplicates+1;continue;end if;insert into public.netflix_accounts(service,current_email,account_type,status,created_by) values(v_service,v_email,coalesce(nullif(trim(p_account_type),''),'Cuenta completa'),'available',v_actor);v_inserted:=v_inserted+1;end loop;return jsonb_build_object('success',true,'inserted',v_inserted,'duplicates',v_duplicates,'invalid',v_invalid);end;$$;
revoke all on function public.bulk_add_service_accounts(text,text,text[]) from public,anon;grant execute on function public.bulk_add_service_accounts(text,text,text[]) to authenticated;

create or replace function public.bulk_assign_service_accounts(p_service text,p_account_emails text[],p_distributor_id uuid,p_starts_on date) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_service text:=lower(trim(p_service));v_raw text;v_email text;v_id uuid;v_status public.account_status;v_assigned int:=0;v_unavailable int:=0;v_not_found int:=0;
begin if not private.is_admin() then raise exception 'Solo el administrador puede realizar esta asignación.';end if;if not exists(select 1 from public.profiles where id=p_distributor_id and role='reseller' and status='active') then raise exception 'Distribuidor no válido.';end if;foreach v_raw in array p_account_emails loop v_email:=lower(trim(coalesce(v_raw,'')));v_id:=null;select id,status into v_id,v_status from public.netflix_accounts where service=v_service and lower(current_email)=v_email for update;if v_id is null then v_not_found:=v_not_found+1;continue;end if;if v_status<>'available' then v_unavailable:=v_unavailable+1;continue;end if;update public.account_assignments set status='cancelled' where account_id=v_id and status='active';insert into public.account_assignments(account_id,seller_id,buyer_reseller_id,starts_on,duration_days,status,created_by) values(v_id,v_actor,p_distributor_id,p_starts_on,30,'active',v_actor);update public.netflix_accounts set current_reseller_id=p_distributor_id,current_client_id=null,status='assigned' where id=v_id;v_assigned:=v_assigned+1;end loop;return jsonb_build_object('success',true,'assigned',v_assigned,'unavailable',v_unavailable,'not_found',v_not_found);end;$$;
revoke all on function public.bulk_assign_service_accounts(text,text[],uuid,date) from public,anon;grant execute on function public.bulk_assign_service_accounts(text,text[],uuid,date) to authenticated;

create or replace function public.admin_edit_service_account(p_account_id uuid,p_service text,p_email text,p_account_type text,p_owner_id uuid,p_starts_on date) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_service text:=lower(trim(p_service));v_email text:=lower(trim(p_email));begin if not private.is_admin() then raise exception 'Solo el administrador puede editar cuentas.';end if;if v_service not in('netflix','spotify') then raise exception 'Plataforma no válida.';end if;if v_email!~'^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'Correo no válido.';end if;if exists(select 1 from public.netflix_accounts where service=v_service and lower(current_email)=v_email and id<>p_account_id) then raise exception 'Ese correo ya existe en la misma plataforma.';end if;if p_owner_id is not null and not exists(select 1 from public.profiles where id=p_owner_id and role='reseller' and status='active') then raise exception 'Propietario no válido.';end if;update public.account_assignments set status='cancelled' where account_id=p_account_id and status='active';if p_owner_id is not null then insert into public.account_assignments(account_id,seller_id,buyer_reseller_id,starts_on,duration_days,status,created_by) values(p_account_id,v_actor,p_owner_id,p_starts_on,30,'active',v_actor);end if;update public.netflix_accounts set service=v_service,current_email=v_email,account_type=coalesce(nullif(trim(p_account_type),''),'Cuenta completa'),current_reseller_id=p_owner_id,current_client_id=null,status=case when p_owner_id is null then 'available' else 'assigned' end where id=p_account_id;return jsonb_build_object('success',true,'message','Cuenta actualizada correctamente.');end;$$;
revoke all on function public.admin_edit_service_account(uuid,text,text,text,uuid,date) from public,anon;grant execute on function public.admin_edit_service_account(uuid,text,text,text,uuid,date) to authenticated;

create or replace function public.create_support_ticket_v2(p_service text,p_reported_email text,p_title text,p_category text,p_description text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid());v_service text:=lower(trim(p_service));v_email text:=lower(trim(p_reported_email));v_account uuid;v_ticket public.support_tickets;begin if v_service not in('netflix','spotify') then raise exception 'Plataforma no válida.';end if;if p_category not in('Caída','Falla','Contraseña incorrecta') then raise exception 'Categoría no válida.';end if;select id into v_account from public.netflix_accounts where service=v_service and lower(current_email)=v_email and private.can_view_account(id) limit 1;if v_account is null then raise exception 'No se encontró una cuenta visible con ese correo y plataforma.';end if;insert into public.support_tickets(created_by,account_id,title,category,description,status,account_email_snapshot,service,reported_email) values(v_user,v_account,trim(p_title),p_category,coalesce(nullif(trim(p_description),''),trim(p_title)),'open',v_email,v_service,v_email) returning * into v_ticket;insert into public.ticket_messages(ticket_id,author_id,message,is_system) values(v_ticket.id,v_user,coalesce(nullif(trim(p_description),''),trim(p_title)),false);return jsonb_build_object('success',true,'message','Ticket creado correctamente.','ticket_id',v_ticket.id,'ticket_number',v_ticket.ticket_number);end;$$;
revoke all on function public.create_support_ticket_v2(text,text,text,text,text) from public,anon;grant execute on function public.create_support_ticket_v2(text,text,text,text,text) to authenticated;

create or replace function public.replace_service_account(p_account_id uuid,p_new_email text,p_ticket_id uuid default null,p_reason text default 'Cambio por garantía') returns jsonb language plpgsql security definer set search_path='' as $$
declare v_user uuid:=(select auth.uid());v_old text;v_service text;v_new text:=lower(trim(p_new_email));begin if not private.is_staff() then raise exception 'Solo administración o soporte pueden reemplazar cuentas.';end if;select current_email,service into v_old,v_service from public.netflix_accounts where id=p_account_id for update;if v_old is null then raise exception 'La cuenta no existe.';end if;if exists(select 1 from public.netflix_accounts where service=v_service and lower(current_email)=v_new and id<>p_account_id) then raise exception 'El correo nuevo ya existe.';end if;update public.netflix_accounts set current_email=v_new where id=p_account_id;insert into public.account_change_history(account_id,ticket_id,old_email,new_email,change_type,reason,performed_by,service) values(p_account_id,p_ticket_id,v_old,v_new,'Cambio por garantía',p_reason,v_user,v_service);if p_ticket_id is not null then insert into public.ticket_messages(ticket_id,author_id,message,is_system) values(p_ticket_id,v_user,'Cuenta asignada exitosamente. Cuenta nueva: '||v_new,true);update public.support_tickets set status='closed',assigned_support_id=v_user,closed_at=now() where id=p_ticket_id;end if;return jsonb_build_object('success',true,'message','Cuenta reemplazada. Las fechas se conservaron.','old_email',v_old,'new_email',v_new);end;$$;
revoke all on function public.replace_service_account(uuid,text,uuid,text) from public,anon;grant execute on function public.replace_service_account(uuid,text,uuid,text) to authenticated;

create or replace function public.send_distributor_notification(p_recipient_ids uuid[],p_include_descendants boolean,p_title text,p_message text,p_image_url text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_sender uuid:=(select auth.uid());v_notification uuid;v_count int;begin if not private.is_admin() then raise exception 'Solo el administrador puede enviar notificaciones.';end if;if coalesce(array_length(p_recipient_ids,1),0)=0 then raise exception 'Selecciona al menos un distribuidor.';end if;insert into public.notifications(sender_id,title,message,image_url) values(v_sender,trim(p_title),trim(p_message),nullif(trim(coalesce(p_image_url,'')),'')) returning id into v_notification;with recursive tree as(select p.id,array[p.id]::uuid[] path from public.profiles p where p.id=any(p_recipient_ids) and p.role='reseller' and p.status='active' union all select c.id,tree.path||c.id from public.profiles c join tree on c.parent_id=tree.id where coalesce(p_include_descendants,false) and c.role='reseller' and c.status='active' and not c.id=any(tree.path)),unique_ids as(select distinct id from tree) insert into public.notification_recipients(notification_id,recipient_id) select v_notification,id from unique_ids on conflict do nothing;select count(*) into v_count from public.notification_recipients where notification_id=v_notification;return jsonb_build_object('success',true,'recipients',v_count);end;$$;
revoke all on function public.send_distributor_notification(uuid[],boolean,text,text,text) from public,anon;grant execute on function public.send_distributor_notification(uuid[],boolean,text,text,text) to authenticated;
create or replace function public.mark_notification_read(p_recipient_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ begin update public.notification_recipients set read_at=coalesce(read_at,now()) where id=p_recipient_id and recipient_id=(select auth.uid());return found;end;$$;
revoke all on function public.mark_notification_read(uuid) from public,anon;grant execute on function public.mark_notification_read(uuid) to authenticated;

grant select,insert,update,delete on public.netflix_accounts to authenticated;grant select,insert on public.account_change_history to authenticated;grant select,insert,update on public.support_tickets to authenticated;grant select,insert,update,delete on public.entertainment_content to authenticated;grant usage,select on all sequences in schema public to authenticated;
select 'BLOQUE 5 CREADO CORRECTAMENTE' as resultado;
